### ISSUE TITLE
响应数据的控制

### ISSUE THREAD

**Issue by cleverpp** [kayuanweb/rap2-delos#10]
场景：响应参数是Array类型，长度为n(>2)，我需要其中1项的某个属性为特定值，剩余项的属性为另外的值
例如：
{
    lists:[
              {isSelect:'1', name:'xxx'},
              {isSelect:'0', name:'xxx'},
              {isSelect:'0', name:'xxx'}
            ]
}

**Comment by wxungang** [comment]
> 场景：响应参数是Array类型，长度为n(>2)，我需要其中1项的某个属性为特定值，剩余项的属性为另外的值
> 例如：
> {
> lists:[
> {isSelect:'1', name:'xxx'},
> {isSelect:'0', name:'xxx'},
> {isSelect:'0', name:'xxx'}
> ]
> }

已解决：https://github.com/kayuanweb/Mock/wiki/api

**Comment by cleverpp** [comment]
先采用copy代码到node_modules中的方式，使用该功能。后续publish到npm库

**Comment by wxungang** [comment]
npm install kayuan-mockjs
