### ISSUE TITLE
mock边界条件时，应全量复制mock-1（默认）

### ISSUE THREAD

**Issue by cleverpp** [kayuanweb/rap2-delos#6]
**您提出的功能是否和您遇到的问题有关，请描述该问题**
新增mock边界时，导入的请求参数、响应参数均缺失，需要手动输入

**您是否有建议的实现方案**
每次新增边界时，应默认全量复制mock-1，然后再由用户修改所需的边界场景，避免用户手动输入大量请求/响应

**其它帮助我们理解您需求的描述、截图**

**Comment by wxungang** [comment]
收到。
